workflows:
  default:
    name: Build Expo App
    instance_type: mac_mini_m2
    max_build_duration: 60
    scripts:
      - npm install
      - npx eas build --platform android --non-interactive --local
    artifacts:
      - "*.apk"
