workflows:
  android-build:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android App
        script: |
          # إضافة --info لنرى الخطأ الحقيقي الذي يمنع الـ Bundle
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
          cd android
          ./gradlew assembleRelease --info
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
