workflows:
  android-build:
    name: Build Android APK
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      # نحدد نسخة node المطلوبة
      node: 20
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Android App
        script: |
          npx eas build --platform android --non-interactive --local
    artifacts:
      - "*.apk"
