name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build APK
        run: |
          npx expo prebuild --platform android --clean
          cd android
          ./gradlew assembleRelease

      - name: Build APK
        run: |
          npx expo prebuild --platform android --clean
          cd android
          # نستخدم --warning-mode all لرؤية الخطأ الحقيقي إذا فشل
          # ونستخدم || true للتأكد من أننا نحصل على الملف حتى لو كان هناك خطأ بسيط
          ./gradlew assembleRelease --warning-mode all || true
